# Generated by Django 5.0.4 on 2024-04-26 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendiente',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pendiente',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
